version: "3"

services:
  server_mini:
    build:
      context: ./server
    container_name: server_mini

  nginxer:
    image: nginx:latest
    container_name: nginxer
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server_mini
